name: Main
on:
    push:
        branches: [main]
    pull-request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: GitHub
            uses: actions/checkout@v4
        
        - name: Podpięcie Node,js
            uses: actions/setup-node@v2
            with:
            node-version: "18.x"
        
        - name: Instalacja dependencji
            run: npm install
        
        - name: Uruchomienie testów
            run: npm run test
    
    deploy: 
        runs-on: ubuntu-latest
        needs: [build]
        steps:
        - name: Krok 1
          uses: actions/checkout@v4
        - name: Krok 2
          uses: azure/appservice-build@v3
          with:
            platform: nodejs
            version: 18.18.0
        - name Wdrożenie aplikacju na Azure/AppService
          uses: azure/webapps-deploy@v1
          with: 
            app-name: SecondNodeApp
            publish-profile: ${{secrets.AZURE_WEB_PROFILE}}

